plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.143'
    id "com.hypherionmc.modutils.modpublisher" version "2.2.2"
    id 'idea'
}

apply from: 'optimization_utils.gradle'

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = minecraft_version + "-" + mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

println('Java: ' + System.getProperty('java.version') + ' | JVM: ' + System.getProperty('java.vm.version') + ' (' + System.getProperty('java.vendor') + ') | Arch: ' + System.getProperty('os.arch'))

sourceSets {
    main
    test {
        compileClasspath += main.output
    }
    generated
    datagen {
        compileClasspath += main.output
    }
}

configurations {
    extendConfigurations(implementation, datagenImplementation)
    extendConfigurations(compileOnly, datagenCompileOnly)
    extendConfigurations(runtimeOnly, datagenRuntimeOnly)
}

static void extendConfigurations(Configuration base, Configuration... configurations) {
    for (configuration in configurations) {
        configuration.extendsFrom(base)
    }
}

neoForge {
    version = project.neo_version
    addModdingDependenciesTo sourceSets.test
    addModdingDependenciesTo sourceSets.datagen

    validateAccessTransformers = true

    runs {
        client {
            client()
            devLogin = true
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        clientData {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG

            // If the selected toolchain is a JBR, enable DCEVM for improved hotswapping
            if (it.project.javaToolchains.launcherFor(java.toolchain).map { it.metadata.vendor }.getOrElse("").contains("JetBrains")) {
                jvmArguments.addAll '-XX:+AllowEnhancedClassRedefinition', '-XX:NonProfiledCodeHeapSize=256M', '-XX:ReservedCodeCacheSize=300M'
            }

            systemProperties.put('terminal.jline', "true")
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
            sourceSet(sourceSets.test)
            sourceSet(sourceSets.datagen)
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    exclude ".cache"
}

repositories {
    mavenLocal()
}

dependencies {
    implementation 'org.jetbrains:annotations:26.0.2'
}

tasks.named("processResources", ProcessResources).configure {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_version            : mod_version
    ]

    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand(replaceProperties)
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

java {
    withSourcesJar()
    withJavadocJar()
}

artifacts {
    archives sourcesJar
    archives javadocJar
}

tasks.named('sourcesJar', Jar).configure {
    from sourceSets.main.allSource
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
            artifact sourcesJar
            artifact javadocJar
        }
    }
    repositories {
        maven {
            name "AnonymousHacker1279"

            String baseMavenUrl = "https://maven.anonymoushacker1279.tech/"
            url mod_version.contains("SNAPSHOT") ? baseMavenUrl + "snapshots" : baseMavenUrl + "releases"

            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}

if (file("RELEASE_NOTES.md").exists()) {
    publisher {
        apiKeys {
            // Load API keys from tokens.properties file
            Properties tokens = new Properties()
            file("tokens.properties").withInputStream {
                stream -> tokens.load(stream)
            }

            curseforge = tokens.getProperty("curseforge")
            modrinth = tokens.getProperty("modrinth")
        }

        setDebug(false)
        setCurseID("1442572")
        setModrinthID("gENo9K7n")
        setGithubRepo("AnonymousHacker1279/OpenPortals")
        setVersionType("release")
        // Read the contents of the RELEASE_NOTES.md file
        setChangelog(file("RELEASE_NOTES.md").text)
        setVersion("v" + mod_version)
        setDisplayName("OpenPortals - v" + mod_version)
        setGameVersions([minecraft_version])
        setLoaders("neoforge")
        setCurseEnvironment("both")
        setArtifact(tasks.jar)
        setJavaVersions([JavaVersion.VERSION_25])
        addAdditionalFile(javadocJar, sourcesJar)
    }
} else {
    println("No RELEASE_NOTES.md found, publishing outside of Maven is disabled.")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}