modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/AnonymousHacker1279/OpenPortals/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "OpenPortals"
bannerFile = "banner.png"
iconFile = "icon.png"
credits = "Currently maintained by AnonymousHacker1279 - Former Authors: AzureDoom, kyrptonaught, Waterpicker, Mysticpasta1"
authors = "AnonymousHacker1279"
description = '''
Easily implement custom portals!
'''

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mixins.openportals.json"